name: nerf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - pytorch>=1.6
  - imageio
  - numpy
  - pyyaml
  - tensorboard
  - torchvision
  - tqdm
  - pip:
    - opencv-python-headless
    - "git+https://github.com/aliutkus/torchsearchsorted#egg=torchsearchsorted"
